var configData = {
    // RACE CONFIGURATIONS
    RACE_INTERVAL: 1,
    RACE_PENDING: 0,
    RACE_PROCESSING: 1,
    RACE_PROCESSED: 3,
    RACE_CANCELLED: 9,
    
    // TRACK CONFIGURATIONS
    TRACK_ID_GENERATOR_RANGE: 1000000,
    
    TRACK_MAINTAIN_TEMPERATURE_PERCENTAGE: 70,
    
    TRACK_START_TEMPERATURE_MIN: 20,
    TRACK_START_TEMPERATURE_RANGE: 16,
    
    TRACK_STRAIGHTS_PERCENTAGE_MIN: 20,
    TRACK_STRAIGHTS_PERCENTAGE_RANGE: 60,
    
    TRACK_STRAIGHTS_AVG_SPEED_MIN: 130,
    TRACK_STRAIGHTS_AVG_SPEED_RANGE: 90,
    
    TRACK_CURVES_AVG_SPEED_MIN: 70,
    TRACK_CURVES_AVG_SPEED_RANGE: 70,
    
    TRACK_LENGTH_MIN: 3000,
    TRACK_LENGTH_RANGE: 3000,
    
    TRACK_PERFORMANCE_RELEVANCE_ENGINE_MIN: 50,
    TRACK_PERFORMANCE_RELEVANCE_ENGINE_RANGE: 20,
    TRACK_PERFORMANCE_RELEVANCE_DRIVER_MIN: 10,
    TRACK_PERFORMANCE_RELEVANCE_DRIVER_RANGE: 10,
    
    // DRIVER CONFIGURATIONS
    DRIVER_ID_GENERATOR_RANGE: 1000000,
    
    DRIVER_SPEED_MIN: 1,
    DRIVER_SPEED_RANGE: 4,
    
    DRIVER_RELIABILITY_MIN: 1,
    DRIVER_RELIABILITY_RANGE: 4,
    
    DRIVER_CONSISTENCY_MIN: 1,
    DRIVER_CONSISTENCY_RANGE: 4,
    
    DRIVER_OVERTAKING_MIN: 1,
    DRIVER_OVERTAKING_RANGE: 4,
    
    DRIVER_DEFENDING_MIN: 1,
    DRIVER_DEFENDING_RANGE: 4,
    
    DRIVER_PUSH_LAPS_MIN: 2,
    DRIVER_PUSH_LAPS_RANGE: 3,
    
    DRIVER_PUSH_LAPS_ADDITIONAL_RISK_PERCENTAGE_MIN: 1,
    DRIVER_PUSH_LAPS_ADDITIONAL_RISK_PERCENTAGE_RANGE: 3,
    
    DRIVER_ERROR_LOST_TIME_MIN: 1,
    DRIVER_ERROR_LOST_TIME_RANGE: 20,
    
    // ENGINE CONFIGURATIONS
    ENGINE_ID_GENERATOR_RANGE: 1000000,
    
    ENGINE_RELIABILITY_MIN: 70,
    ENGINE_RELIABILITY_RANGE: 25,
    
    ENGINE_FUEL_CONSUMPTION_RATE_MIN: 50,
    ENGINE_FUEL_CONSUMPTION_RATE_RANGE: 26,
    
    ENGINE_FUEL_TANK_SIZE_MIN: 100,
    ENGINE_FUEL_TANK_SIZE_RANGE: 20,
    
    ENGINE_HP_MIN: 770,
    ENGINE_HP_RANGE: 75,
    
    ENGINE_HP_LOSS_RATE_PER_FUEL_LITER: 0.3,
    ENGINE_FUEL_CONSUMPTION_STANDARD_DEVIATION: 3,
    
    ENGINE_RANDOM_PROBLEM_PERFORMANCE_LOSS_MIN: 1,
    ENGINE_RANDOM_PROBLEM_PERFORMANCE_LOSS_RANGE: 30,
    
    // TIRE CONFIGURATIONS
    TIRE_ID_GENERATOR_RANGE: 1000000,
    
    TIRE_WEAR_STANDARD_DEVIATION: 4,
    TIRE_WEAR_TEMPERATURE_WEAR_CONSTANT_1: 5,
    TIRE_WEAR_TEMPERATURE_WEAR_CONSTANT_2: 4,
    TIRE_PERFORMANCE_DROP_RATE: 5,
    
    TIRE_SOFT_KM_AT_20_CELSIUS_MIN: 100,
    TIRE_SOFT_KM_AT_20_CELSIUS_RANGE: 20,
    
    TIRE_MEDIUM_KM_AT_20_CELSIUS_MIN: 150,
    TIRE_MEDIUM_KM_AT_20_CELSIUS_RANGE: 20,
    
    TIRE_HARD_KM_AT_20_CELSIUS_MIN: 205,
    TIRE_HARD_KM_AT_20_CELSIUS_RANGE: 30,
    
    TIRE_SOFT_PERFORMANCE_PERCENTAGE: 100,
    TIRE_MEDIUM_PERFORMANCE_PERCENTAGE_MIN: 88,
    TIRE_MEDIUM_PERFORMANCE_PERCENTAGE_RANGE: 4,
    TIRE_HARD_PERFORMANCE_PERCENTAGE_MIN: 77,
    TIRE_HARD_PERFORMANCE_PERCENTAGE_RANGE: 6,
    
    TIRE_BLOWN_PERFORMANCE_PERCENTAGE_MIN: 20,
    TIRE_BLOWN_PERFORMANCE_PERCENTAGE_RANGE: 20,
    
    // CAR CONFIGURATIONS
    CAR_WEIGHT_MIN: 600
};

module.exports = configData;