var configData = {
    RACE_INTERVAL: 1,
    
    START_TEMPERATURE_MINIMUM: 20,
    START_TEMPERATURE_RANGE: 16,
    
    TRACK_STRAIGHTS_PERCENTAGE_MINIMUM: 20,
    TRACK_STRAIGHTS_PERCENTAGE_RANGE: 60,
    TRACK_STRAIGHTS_AVG_SPEED_MINIMUM: 130,
    TRACK_STRAIGHTS_AVG_SPEED_RANGE: 90,
    
    TRACK_CURVES_AVG_SPEED_MINIMUM: 70,
    TRACK_CURVES_AVG_SPEED_RANGE: 70,
    
    TRACK_LENGTH_MINIMUM: 3000,
    TRACK_LENGTH_RANGE: 3000,
    
    TRACK_ID_GENERATOR_RANGE: 1000000,
    
    DRIVER_ID_GENERATOR_RANGE: 1000000,
    
    DRIVER_SPEED_MIN: 1,
    DRIVER_SPEED_RANGE: 4,
    
    DRIVER_RELIABILITY_MIN: 1,
    DRIVER_RELIABILITY_RANGE: 4,
    
    DRIVER_CONSISTENCY_MIN: 1,
    DRIVER_CONSISTENCY_RANGE: 4,
    
    DRIVER_OVERTAKING_MIN: 1,
    DRIVER_OVERTAKING_RANGE: 4,
    
    DRIVER_DEFENDING_MIN: 1,
    DRIVER_DEFENDING_RANGE: 4
};

module.exports = configData;